# Generated by Django 2.1 on 2018-08-03 08:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agree',
            fields=[
                ('AID', models.AutoField(primary_key=True, serialize=False)),
                ('Agree', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('MID', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CID', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(max_length=1000)),
                ('MID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MessageBoard.Board')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MessageBoard.User'),
        ),
        migrations.AddField(
            model_name='board',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MessageBoard.User'),
        ),
        migrations.AddField(
            model_name='agree',
            name='MID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MessageBoard.Board', unique=True),
        ),
        migrations.AddField(
            model_name='agree',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MessageBoard.User', unique=True),
        ),
    ]
