# Generated by Django 2.1 on 2018-08-04 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageBoard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agree',
            old_name='Agree',
            new_name='agree',
        ),
    ]
