# Generated by Django 2.1 on 2018-08-05 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MessageBoard', '0002_auto_20180804_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agree',
            name='MID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MessageBoard.Board'),
        ),
        migrations.AlterField(
            model_name='agree',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MessageBoard.User'),
        ),
    ]
